from typing import Protocol

from src.domain.models import CandidateIdentity, ShortlistReport


class CandidateRepository(Protocol):
    async def get(self, canonical_id: str) -> CandidateIdentity | None: ...
    async def upsert(self, identity: CandidateIdentity) -> None: ...


class PipelineRunRepository(Protocol):
    async def create(self, run_id: str, jd: str, location: str, work_mode: str) -> None: ...
    async def complete(self, run_id: str) -> None: ...
    async def fail(self, run_id: str, error: str) -> None: ...


class ShortlistReportRepository(Protocol):
    async def save(self, run_id: str, report: ShortlistReport) -> None: ...
